### ISSUE TITLE
Do not depend on dev-master of php-webdriver

### ISSUE THREAD

**Issue by OndraM** [applitools/eyes.sdk.php#1]
Hi,
I just noted this library, it is great to see Applitools library being made for PHP as well! 

I also noted you depend on dev-master of php-webdriver. I would definitely recommend to depend rather on ~1.1 version, because the dev-master refers to master branch, which is obsolete and no longer maintained (and also does not use namespaces). 

The active development is currently in branch "community", but anyway, depending on branch instead of specific version is dangerous (the API of the library may change any time). Thus using version ~1.1 would be much better choice.

**Comment by itaibh** [comment]
Thank you.
I changed that and we are now using php-webdriver version 1.4.
