### ISSUE TITLE
Tests will fail for Linux 

### ISSUE THREAD

**Issue by Free1man** [applitools/eyes.sdk.php#16]
Using v1.2.1

I'm running test in Linux docker container:
$ docker run -d -p 4444:4444 -p 5900:5900 -v /dev/shm:/dev/shm selenium/standalone-chrome-debug:3.8.1-bohrium

But probly it will fail in real no docker Linux.

In file: vendor/applitools/eyes.sdk.php/eyes.selenium.php/UserAgent.php
Error will ocuur:
`Undefined index: major in vendor/applitools/eyes.sdk.php/eyes.selenium.php/UserAgent.php line 119`

It happens because there is no major version in  $result->OSMajorVersion array. 

Probably this code should be optional: 
```
 if (count($osmatch) > 1) 
  {
                $result->OSMajorVersion = $osmatch["major"];
                $result->OSMinorVersion = $osmatch["minor"];
  }
```

  
  Worked fine in v0.3

**Comment by itaibh** [comment]
Fixed in version v1.2.2
