### ISSUE TITLE
Specify type of the parameter or the return value

### ISSUE THREAD

**Issue by mvondr** [applitools/eyes.sdk.php#2]
It would be correct to specify type of the parameter or the return value in PHPDoc block. It is (also) used by IDEs to provide type control.

Examples:
1.@return

```
/**
 * @return string The currently set API key or {@code null} if no key is set.
 */
public function getApiKey()
...
```

2.@param type $variable

```
/**
 * Sets the API key of your applitools Eyes account.
 *
 * @param string $apiKey The api key to set.
 */
public function setApiKey($apiKey)
...
```

**Comment by itaibh** [comment]
Hi MVO2015.
Indeed that is a required changed and I've started updating the documentation blocks in the files.
A lot of it is already committed and pushed and you can try the most recent development snapshot if you want to see that.
However, this is a work in progress and far from finished, so for now I keep that issue open (as a reminder, mostly). I'll close it before we'll make a release.

**Comment by itaibh** [comment]
Most of the documentation is already fixed at this point, so I'm closing this issue.
If you find specific places that bother you please open another issue.
