### ISSUE TITLE
Do not require phpunit dependency

### ISSUE THREAD

**Issue by OndraM** [applitools/eyes.sdk.php#7]
Hi, 
the PHPUnit dependency (defined in composer.json) should IMO be omitted - it is not required dependency for the library itself, and PHPUnit is only one possible way how to execute Selenium tests (but you could run them using some completely different test runner).

The PHPUnit should be defined only as a dev-dependency, so that it could be used to execute unit tests of the library - see https://getcomposer.org/doc/04-schema.md#require-dev or http://stackoverflow.com/questions/16679589/whats-the-difference-between-require-and-require-dev .

Also we use already use PHPUnit in our project, however still version 5.x, so we cannot install the Applitools SKD right now because of this (unnecessary) version conflict...

**Comment by itaibh** [comment]
Thanks!
Pull request merged.
